s = set()
a = int(input( " Enter the no. "))
s.add(a)
a = int(input( " Enter the no. "))
s.add(a)
a = int(input( " Enter the no. "))
s.add(a)
a = int(input( " Enter the no. "))
s.add(a)
a = int(input( " Enter the no. "))
s.add(a)
a = int(input( " Enter the no. "))
s.add(a)
a = int(input( " Enter the no. "))
s.add(a)

print(s)